<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thème 4: ANOVA à deux facteur</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LIVRABLE_S4_files/libs/clipboard/clipboard.min.js"></script>
<script src="LIVRABLE_S4_files/libs/quarto-html/quarto.js"></script>
<script src="LIVRABLE_S4_files/libs/quarto-html/popper.min.js"></script>
<script src="LIVRABLE_S4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LIVRABLE_S4_files/libs/quarto-html/anchor.min.js"></script>
<link href="LIVRABLE_S4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LIVRABLE_S4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LIVRABLE_S4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LIVRABLE_S4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LIVRABLE_S4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="LIVRABLE_S4_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="LIVRABLE_S4_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="LIVRABLE_S4_files/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#partie-1-anova-à-deux-facteurs-controlés-cellules-équilibrées" id="toc-partie-1-anova-à-deux-facteurs-controlés-cellules-équilibrées" class="nav-link active" data-scroll-target="#partie-1-anova-à-deux-facteurs-controlés-cellules-équilibrées"><span class="header-section-number">1</span> Partie 1: ANOVA à deux facteurs controlés cellules équilibrées</a>
  <ul class="collapse">
  <li><a href="#anova-à-deux-facteurs-contrôlés" id="toc-anova-à-deux-facteurs-contrôlés" class="nav-link" data-scroll-target="#anova-à-deux-facteurs-contrôlés"><span class="header-section-number">1.1</span> ANOVA à deux facteurs contrôlés</a></li>
  <li><a href="#cadre-théorique" id="toc-cadre-théorique" class="nav-link" data-scroll-target="#cadre-théorique"><span class="header-section-number">1.2</span> Cadre théorique</a></li>
  <li><a href="#anova-à-deux-facteurs-controlés-avec-cellules-équilibrées" id="toc-anova-à-deux-facteurs-controlés-avec-cellules-équilibrées" class="nav-link" data-scroll-target="#anova-à-deux-facteurs-controlés-avec-cellules-équilibrées"><span class="header-section-number">1.3</span> ANOVA à deux facteurs controlés avec cellules équilibrées</a></li>
  <li><a href="#hypothèses-générales-dintérêt" id="toc-hypothèses-générales-dintérêt" class="nav-link" data-scroll-target="#hypothèses-générales-dintérêt"><span class="header-section-number">1.4</span> Hypothèses générales d’intérêt</a></li>
  <li><a href="#méthodologie" id="toc-méthodologie" class="nav-link" data-scroll-target="#méthodologie"><span class="header-section-number">1.5</span> Méthodologie</a></li>
  <li><a href="#les-tests-dhypothèses-appropriées-dans-le-contexte-danova-à-deux-facteurs" id="toc-les-tests-dhypothèses-appropriées-dans-le-contexte-danova-à-deux-facteurs" class="nav-link" data-scroll-target="#les-tests-dhypothèses-appropriées-dans-le-contexte-danova-à-deux-facteurs"><span class="header-section-number">1.6</span> Les tests d’hypothèses appropriées dans le contexte d’ANOVA à deux facteurs</a></li>
  <li><a href="#test-dinteraction-entre-les-facteurs" id="toc-test-dinteraction-entre-les-facteurs" class="nav-link" data-scroll-target="#test-dinteraction-entre-les-facteurs"><span class="header-section-number">1.7</span> Test d’interaction entre les facteurs</a></li>
  <li><a href="#analyse-fine-des-résultats-lorsque-linteraction-nest-pas-significative" id="toc-analyse-fine-des-résultats-lorsque-linteraction-nest-pas-significative" class="nav-link" data-scroll-target="#analyse-fine-des-résultats-lorsque-linteraction-nest-pas-significative"><span class="header-section-number">1.8</span> Analyse fine des résultats lorsque l’interaction n’est pas significative</a></li>
  <li><a href="#test-dinteraction-entre-les-facteurs-1" id="toc-test-dinteraction-entre-les-facteurs-1" class="nav-link" data-scroll-target="#test-dinteraction-entre-les-facteurs-1"><span class="header-section-number">1.9</span> Test d’interaction entre les facteurs</a></li>
  <li><a href="#analyse-fine-des-résultats-lorsque-linteraction-est-significative" id="toc-analyse-fine-des-résultats-lorsque-linteraction-est-significative" class="nav-link" data-scroll-target="#analyse-fine-des-résultats-lorsque-linteraction-est-significative"><span class="header-section-number">1.10</span> Analyse fine des résultats lorsque l’interaction est significative</a></li>
  <li><a href="#création-des-groupes" id="toc-création-des-groupes" class="nav-link" data-scroll-target="#création-des-groupes"><span class="header-section-number">1.11</span> Création des groupes</a></li>
  <li><a href="#syntaxe-pour-la-création-des-groupes" id="toc-syntaxe-pour-la-création-des-groupes" class="nav-link" data-scroll-target="#syntaxe-pour-la-création-des-groupes"><span class="header-section-number">1.12</span> Syntaxe pour la création des groupes</a></li>
  </ul></li>
  <li><a href="#partie-2-anova-à-deux-facteurs-controlés-cellules-déséquilibrées" id="toc-partie-2-anova-à-deux-facteurs-controlés-cellules-déséquilibrées" class="nav-link" data-scroll-target="#partie-2-anova-à-deux-facteurs-controlés-cellules-déséquilibrées"><span class="header-section-number">2</span> Partie 2: ANOVA à deux facteurs controlés: cellules déséquilibrées</a>
  <ul class="collapse">
  <li><a href="#mise-en-situation-1" id="toc-mise-en-situation-1" class="nav-link" data-scroll-target="#mise-en-situation-1"><span class="header-section-number">2.1</span> Mise en situation 1</a></li>
  <li><a href="#décomposition-de-la-variabilité-totale-anova-à-2-facteurs-avec-cellules-déséquilibrées" id="toc-décomposition-de-la-variabilité-totale-anova-à-2-facteurs-avec-cellules-déséquilibrées" class="nav-link" data-scroll-target="#décomposition-de-la-variabilité-totale-anova-à-2-facteurs-avec-cellules-déséquilibrées"><span class="header-section-number">2.2</span> Décomposition de la variabilité totale: ANOVA à 2 facteurs avec cellules déséquilibrées</a></li>
  <li><a href="#analyse-de-la-variable-don" id="toc-analyse-de-la-variable-don" class="nav-link" data-scroll-target="#analyse-de-la-variable-don"><span class="header-section-number">2.3</span> Analyse de la variable Don</a></li>
  <li><a href="#analyse-de-la-variable-sympathie" id="toc-analyse-de-la-variable-sympathie" class="nav-link" data-scroll-target="#analyse-de-la-variable-sympathie"><span class="header-section-number">2.4</span> Analyse de la variable Sympathie</a></li>
  <li><a href="#analyse-des-effets-simples-des-facteurs-variable-sympathie" id="toc-analyse-des-effets-simples-des-facteurs-variable-sympathie" class="nav-link" data-scroll-target="#analyse-des-effets-simples-des-facteurs-variable-sympathie"><span class="header-section-number">2.5</span> Analyse des effets simples des facteurs (variable Sympathie)</a></li>
  <li><a href="#comparaison-des-moyennes" id="toc-comparaison-des-moyennes" class="nav-link" data-scroll-target="#comparaison-des-moyennes"><span class="header-section-number">2.6</span> Comparaison des moyennes</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">2.7</span> Conclusion&nbsp;:</a></li>
  <li><a href="#mise-en-situation-2" id="toc-mise-en-situation-2" class="nav-link" data-scroll-target="#mise-en-situation-2"><span class="header-section-number">2.8</span> Mise en situation 2</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thème 4: ANOVA à deux facteur</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="partie-1-anova-à-deux-facteurs-controlés-cellules-équilibrées" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="partie-1-anova-à-deux-facteurs-controlés-cellules-équilibrées"><span class="header-section-number">1</span> Partie 1: ANOVA à deux facteurs controlés cellules équilibrées</h2>
<section id="anova-à-deux-facteurs-contrôlés" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="anova-à-deux-facteurs-contrôlés"><span class="header-section-number">1.1</span> ANOVA à deux facteurs contrôlés</h3>
<p><strong>Mise en situation</strong></p>
<p>Pour promouvoir une marque de Robot culinaire haut de gamme, le responsable marketing de la compagnie «&nbsp;RobTech&nbsp;» veut évaluer l’effet de la source et du temps de réflexion (Reflex) sur l’efficacité d’une publicité de type «&nbsp;piecemeal&nbsp;» c.à.d. une publicité comparant la marque en question à une marque concurrente «&nbsp;attribut par attribut&nbsp;».</p>
<p><strong>Design de l’étude</strong></p>
<p>120 sujets ont été assignés au hasard à un des quatre groupes de l’étude et, après avoir vu le message publicitaire, devaient répondre à un questionnaire pour mesurer l’évaluation de la marque cible (échelle de 1 à 15) et la crédibilité accordée au message publicitaire (échelle de 1 à 15).</p>
<p>Deux facteurs ont été manipulés pour créer les différents types de messages :<br>
1) Source des informations du message (SOURCE) : - Selon la brochure d’information de la compagnie «&nbsp;<strong>RobTech</strong>&nbsp;» - Selon le magazine «&nbsp;Protégez vous&nbsp;» 2) Temps de réflexion accordé (REFLEX) : - Temps de réflexion <strong>court</strong><br>
- Temps de réflexion <strong>long</strong></p>
<p><strong>Les données</strong></p>
<p>Le fichier des données simulées correspondant à cette étude se trouve dans le fichier «&nbsp;Robtech_ANOVA_2.csv&nbsp;».</p>
<p><strong>Variables</strong></p>
<p>Après avoir visionné un des messages publicitaires (assignés aléatoirement), les participants devaient évaluer la marque cible et donner un score de crédibilité au message (sur une échelle de 1 à 15).</p>
<p>Source: 1=Brochure du manufacturier; 2= Magasine «&nbsp;Protégez-Vous&nbsp;». Reflex: 1=court; 2=long Eval = Évaluation de la marque de robot Cred = Crédibilité du message</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le fichier CSV </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>robtech <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/THEME 4/data/RobTech_ANOVA_2.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>robtech<span class="sc">$</span>source<span class="ot">&lt;-</span><span class="fu">as.factor</span>(robtech<span class="sc">$</span>source)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>robtech<span class="sc">$</span>reflex<span class="ot">&lt;-</span><span class="fu">as.factor</span>(robtech<span class="sc">$</span>reflex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ce plan d’expérience nous permet de définir 4 groupes (populations) et de comparer les 4 moyennes suivantes, pour chaque variable :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="résultats-observés-échantillons-variable-crédibilite-de-la-marque" class="level4" data-number="1.1.1">
<h4 data-number="1.1.1" class="anchored" data-anchor-id="résultats-observés-échantillons-variable-crédibilite-de-la-marque"><span class="header-section-number">1.1.1</span> Résultats observés (échantillons): variable Crédibilite de la marque</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives (moyenne, écart-type, effectif)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>robtech_stats <span class="ot">&lt;-</span> robtech <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(source, reflex) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(cred, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    É<span class="at">cart_type =</span> <span class="fu">sd</span>(cred, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(robtech_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   source [2]
  source reflex Moyenne Écart_type     N
  &lt;fct&gt;  &lt;fct&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 1      1         7.5        3.45    30
2 1      2         6.4        2.25    30
3 2      1         9.5        2.90    30
4 2      2         8.93       3.07    30</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un graphique des moyennes marginales estimées</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(robtech_stats, <span class="fu">aes</span>(<span class="at">x =</span> source, <span class="at">y =</span> Moyenne, <span class="at">group =</span> reflex, <span class="at">color =</span> reflex)) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>   </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>    </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moyennes marginales estimées de crédibilité"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Source"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Moyenne estimée"</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="résultats-observés-échantillons-variable-évaluation-de-la-marque" class="level4" data-number="1.1.2">
<h4 data-number="1.1.2" class="anchored" data-anchor-id="résultats-observés-échantillons-variable-évaluation-de-la-marque"><span class="header-section-number">1.1.2</span> Résultats observés (échantillons): variable Évaluation de la marque</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives (moyenne, écart-type, effectif)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>robtech_stats2 <span class="ot">&lt;-</span> robtech <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(source, reflex) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(eval, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    É<span class="at">cart_type =</span> <span class="fu">sd</span>(eval, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(robtech_stats2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   source [2]
  source reflex Moyenne Écart_type     N
  &lt;fct&gt;  &lt;fct&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 1      1         9.27       2.74    30
2 1      2         8.03       3.05    30
3 2      1         7.87       2.96    30
4 2      2        10.4        2.69    30</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un graphique des moyennes marginales estimées</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(robtech_stats2, <span class="fu">aes</span>(<span class="at">x =</span> source, <span class="at">y =</span> Moyenne, <span class="at">group =</span> reflex, <span class="at">color =</span> reflex)) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>   </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>    </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moyennes marginales estimées de crédibilité"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Source"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Moyenne estimée"</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="cadre-théorique" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="cadre-théorique"><span class="header-section-number">1.2</span> Cadre théorique</h3>
<p>Le but d’une ANOVA à deux facteurs est d’étudier comment et dans quelle mesure les niveaux des facteurs A et B influencent la moyenne d’une variable d’intérêt Y.</p>
<p>Y: variable dépendante quantitative.</p>
<p>2 facteurs: Facteur A avec a niveaux<br>
Facteur B avec b niveaux</p>
<p>Le croisement des 2 facteurs crée a x b groupes</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tableau des interactions Facteur A &amp; Facteur B</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">Facteur.A</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.2</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">...</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.b</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau 1</td>
<td style="text-align: center;">μ11</td>
<td style="text-align: center;">μ12</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μ1b</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau 2</td>
<td style="text-align: center;">μ21</td>
<td style="text-align: center;">μ22</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μ2b</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau a</td>
<td style="text-align: center;">μa1</td>
<td style="text-align: center;">μa2</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μab</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>μij : moyenne de la variable Y pour le groupe correspondant au ième niveau du facteur A et au jème niveau du facteur B.</p>
<section id="échantillon" class="level4" data-number="1.2.1">
<h4 data-number="1.2.1" class="anchored" data-anchor-id="échantillon"><span class="header-section-number">1.2.1</span> Échantillon</h4>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tableau des interactions Facteur A &amp; Facteur B</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Facteur B
</div></th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">Facteur.A</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.2</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">...</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.b</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau 1</td>
<td style="text-align: center;">Y[111], Y[112], ..., Y[11n1]</td>
<td style="text-align: center;">Y[121], Y[122], ..., Y[12n12]</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">Y[1b1], Y[1b2], ..., Y[1bn1b]</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau 2</td>
<td style="text-align: center;">Y[211], Y[212], ..., Y[21n21]</td>
<td style="text-align: center;">Y[221], Y[222], ..., Y[22n22]</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">Y[2b1], Y[2b2], ..., Y[2bn2b]</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 224, 230, 255) !important;">niveau a</td>
<td style="text-align: center;">Y[a11], Y[a12], ..., Y[a1na]</td>
<td style="text-align: center;">Y[a21], Y[a22], ..., Y[a2na2]</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">Y[ab1], Y[ab2], ..., Y[abnab]</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>𝐧_𝒊𝒋:nombre d’observations dans le groupe correspondant au ième niveau du facteur A et au jème niveau du facteur B (cellule (i,j)) . 𝒀_𝒊𝒋𝒌: observation du kème sujet dans le groupe correspondant au ième niveau du facteur A et au jème niveau du facteur B.</p>
</section>
</section>
<section id="anova-à-deux-facteurs-controlés-avec-cellules-équilibrées" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="anova-à-deux-facteurs-controlés-avec-cellules-équilibrées"><span class="header-section-number">1.3</span> ANOVA à deux facteurs controlés avec cellules équilibrées</h3>
<p>L’utilisation des méthodes statistiques sont différentes selon que les données sont équilibrées ou non. Par données équilibrées, on entend un design ou plan d’expérience où chaque cellule (définissant un groupe) contient le même nombre d’observations.</p>
<p>Dans la mise en situation définie au début du cours, chaque cellule contient 30 observations.</p>
<p><strong>Cas 1: Cellules équilibrées (tous les n_ij sont égaux)</strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tableau des moyennes marginales pour Facteur A et Facteur B</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Facteur B
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">Facteur.A</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">niveau.1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">niveau.2</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">...</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">niveau.b</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">Moyenne.marginale.Facteur.A</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 196, 222, 255) !important;">niveau 1</td>
<td style="text-align: center;">μ11</td>
<td style="text-align: center;">μ21</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μ1b</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">μ1•</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 196, 222, 255) !important;">niveau 2</td>
<td style="text-align: center;">μ12</td>
<td style="text-align: center;">μ22</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μ2b</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">μ2•</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 196, 222, 255) !important;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">...</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 196, 222, 255) !important;">niveau a</td>
<td style="text-align: center;">μa1</td>
<td style="text-align: center;">μa2</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μab</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">μa•</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: rgba(176, 196, 222, 255) !important;">Moyenne marginale Facteur B</td>
<td style="text-align: center;">μ•1</td>
<td style="text-align: center;">μ•2</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">μ•b</td>
<td style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(47, 85, 151, 255) !important;">μ Moyenne globale</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><span class="math display">\[
\mu_{i\bullet} = \frac{1}{b} \sum_{j=1}^{b} \mu_{ij}
\]</span> Moyenne <strong>marginale</strong> du niveau (i) du facteur A.</p>
<p><span class="math display">\[
\mu_{\bullet j} = \frac{1}{a} \sum_{i=1}^{a} \mu_{ij}
\]</span> Moyenne <strong>marginale</strong> du niveau (j) du facteur B.</p>
<p><span class="math display">\[
\mu = \frac{1}{ab} \sum_{i=1}^{a} \sum_{j=1}^{b} \mu_{ij}
\]</span> Moyenne <strong>globale</strong> (moyenne des moyennes).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variable Crédibilité</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Court</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Long</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Moyenne_Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Brochure du manufacturier</td>
<td style="text-align: center;">7.5 (n=30)</td>
<td style="text-align: center;">6.4 (n=30)</td>
<td style="text-align: center; background-color: rgba(217, 226, 243, 255) !important;">6.95 = (7.5+6.4)/2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Protégez vous</td>
<td style="text-align: center;">9.5 (n=30)</td>
<td style="text-align: center;">8.93 (n=30)</td>
<td style="text-align: center; background-color: rgba(217, 226, 243, 255) !important;">9.22</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: red !important;">Moyenne marginale Facteur Reflex</td>
<td style="text-align: center; font-weight: bold; color: red !important;">8.5 = (7.5+9.5)/2</td>
<td style="text-align: center; font-weight: bold; color: red !important;">7.67</td>
<td style="text-align: center; font-weight: bold; color: red !important; background-color: rgba(217, 226, 243, 255) !important;">8.08</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>table_eval</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variable Évaluation</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Source</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Court</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Long</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Moyenne_Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Brochure du manufacturier</td>
<td style="text-align: center;">9.27 (n=30)</td>
<td style="text-align: center;">8.03 (n=30)</td>
<td style="text-align: center; background-color: rgba(217, 226, 243, 255) !important;">8.67 = (9.27+8.03)/2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Protégez vous</td>
<td style="text-align: center;">7.87 (n=30)</td>
<td style="text-align: center;">10.43 (n=30)</td>
<td style="text-align: center; background-color: rgba(217, 226, 243, 255) !important;">9.15</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: red !important;">Moyenne marginale Facteur Reflex</td>
<td style="text-align: center; font-weight: bold; color: red !important;">8.57 = (9.27+7.87)/2</td>
<td style="text-align: center; font-weight: bold; color: red !important;">9.23</td>
<td style="text-align: center; font-weight: bold; color: red !important; background-color: rgba(217, 226, 243, 255) !important;">8.9</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="interaction-entre-les-facteurs" class="level4" data-number="1.3.1">
<h4 data-number="1.3.1" class="anchored" data-anchor-id="interaction-entre-les-facteurs"><span class="header-section-number">1.3.1</span> Interaction entre les facteurs</h4>
<p>On débute une ANOVA à deux facteurs ou plus par une analyse d’interaction entre les facteurs.</p>
<ul>
<li>S’il n’y a pas d’interaction entre 2 facteurs, la différence des moyennes entre 2 niveaux donnés d’un facteur demeure sensiblement la même peu importe le niveau de l’autre facteur et vice-versa.</li>
</ul>
<p><strong>Retour sur l’exemple: Variable ‘’Cred’’</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyennes estimées en fonction de Source</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">ggplot</span>(robtech_stats, <span class="fu">aes</span>(<span class="at">x =</span> source, <span class="at">y =</span> Moyenne, <span class="at">group =</span> reflex, <span class="at">color =</span> reflex)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>   </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Moyenne <span class="sc">-</span> Écart_type, <span class="at">ymax =</span> Moyenne <span class="sc">+</span> Écart_type), <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span>  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Moyennes marginales estimées"</span>, <span class="at">x =</span> <span class="st">"Source"</span>, <span class="at">y =</span> <span class="st">"Moyenne estimée"</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyennes estimées en fonction de Reflex</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(robtech_stats, <span class="fu">aes</span>(<span class="at">x =</span> reflex, <span class="at">y =</span> Moyenne, <span class="at">group =</span> source, <span class="at">color =</span> source)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Moyenne <span class="sc">-</span> Écart_type, <span class="at">ymax =</span> Moyenne <span class="sc">+</span> Écart_type), <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Moyennes marginales estimées"</span>, <span class="at">x =</span> <span class="st">"Temps de réflexion"</span>, <span class="at">y =</span> <span class="st">"Moyenne estimée"</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>S’il y a interaction entre 2 facteurs, la différence des moyennes entre 2 niveaux donnés d’un facteur peut varier selon le niveau de l’autre facteur.</li>
</ul>
<p><strong>Retour sur l’exemple 2: Variable ‘’Eval’’</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyennes estimées en fonction de Source</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(robtech_stats2, <span class="fu">aes</span>(<span class="at">x =</span> source, <span class="at">y =</span> Moyenne, <span class="at">group =</span> reflex, <span class="at">color =</span> reflex)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Moyenne <span class="sc">-</span> Écart_type, <span class="at">ymax =</span> Moyenne <span class="sc">+</span> Écart_type), <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Moyennes marginales estimées"</span>, <span class="at">x =</span> <span class="st">"Source"</span>, <span class="at">y =</span> <span class="st">"Moyenne estimée"</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyennes estimées en fonction de Reflex</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(robtech_stats2, <span class="fu">aes</span>(<span class="at">x =</span> reflex, <span class="at">y =</span> Moyenne, <span class="at">group =</span> source, <span class="at">color =</span> source)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Moyenne <span class="sc">-</span> Écart_type, <span class="at">ymax =</span> Moyenne <span class="sc">+</span> Écart_type), <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Moyennes marginales estimées"</span>, <span class="at">x =</span> <span class="st">"Temps de réflexion"</span>, <span class="at">y =</span> <span class="st">"Moyenne estimée"</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="hypothèses-générales-dintérêt" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="hypothèses-générales-dintérêt"><span class="header-section-number">1.4</span> Hypothèses générales d’intérêt</h3>
<ol type="1">
<li>Existe-t-il une interaction entre les facteurs A et B ?</li>
</ol>
<p><span class="math display">\[ H_{0AB} : \mu_{ij} - \mu_{im} - \mu_{lj} + \mu_{lm} = 0 \quad \text{pour tout } (i,j,l,m) \quad \text{(pas d'interaction)} \]</span><br>
<span class="math display">\[ H_{1AB} : \mu_{ij} - \mu_{im} - \mu_{lj} + \mu_{lm} \neq 0 \quad \text{pour au moins un } (i,j,l,m) \quad \text{(interaction)} \]</span></p>
<ol start="2" type="1">
<li>Test sur l’effet global du facteur A</li>
</ol>
<p><span class="math display">\[ H_{0A} : \mu_{1\bullet} = \mu_{2\bullet} = \cdots = \mu_{a\bullet} \]</span><br>
<span class="math display">\[ H_{1A} : \text{les } \mu_{i\bullet} \text{ ne sont pas tous égaux.} \]</span><br>
<em>(l’effet global du facteur A est significatif)</em></p>
<ol start="3" type="1">
<li>Test sur l’effet global du facteur B</li>
</ol>
<p><span class="math display">\[ H_{0B} : \mu_{\bullet 1} = \mu_{\bullet 2} = \cdots = \mu_{\bullet b} \]</span><br>
<span class="math display">\[ H_{1B} : \text{les } \mu_{\bullet j} \text{ ne sont pas tous égaux.} \]</span><br>
<em>(l’effet global du facteur B est significatif)</em></p>
</section>
<section id="méthodologie" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="méthodologie"><span class="header-section-number">1.5</span> Méthodologie</h3>
<p>On commence par tester s’il y a interaction (H0_AB)</p>
<ul>
<li><p><strong>Si on ne rejette pas l’hypothèse H0_AB</strong> (aucune interaction significative n’a été détectée), on pourra alors poursuivre l’analyse et tester les <strong>effets globaux H0_A et H0_B</strong> à partir du même tableau d’Anova (<strong>Tests of Between-Sujects Effects</strong>).</p></li>
<li><p><strong>Si on rejette l’hypothèse H0_AB</strong>, alors l’interaction est significative (l’effet du facteur A n’est pas le même pour tous les niveaux du facteur B). Il ne servira à rien de tester les effets globaux H0A et H0B. On devra plutôt comparer les niveaux du facteur A à l’intérieur de chaque niveau du facteur B et vice-versa. Ce type d’effets est appelé « <strong>effet simple</strong> » et sera abordé plus loin.</p></li>
</ul>
<p>L’analyse pourra par la suite être raffinée en procédant à des <strong>comparaisons multiples</strong> comme dans le cas de l’ANOVA à un facteur contrôlé.</p>
<section id="échantillons" class="level4" data-number="1.5.1">
<h4 data-number="1.5.1" class="anchored" data-anchor-id="échantillons"><span class="header-section-number">1.5.1</span> Échantillons</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tableau des moyennes marginales</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">Facteur.A</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.2</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">...</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">niveau.b</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(0, 115, 194, 255) !important;">Moyenne.Facteur.A</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">niveau 1</td>
<td style="text-align: center;">Ȳ₁₁.</td>
<td style="text-align: center;">| Ȳ₂₁.</td>
<td style="text-align: center;">| ..</td>
<td style="text-align: center;">| Ȳₐ₁.</td>
<td style="text-align: center;">| Ȳ.₁.</td>
</tr>
<tr class="even">
<td style="text-align: center;">niveau 2</td>
<td style="text-align: center;">Ȳ₁₂.</td>
<td style="text-align: center;">| Ȳ₂₂.</td>
<td style="text-align: center;">| ..</td>
<td style="text-align: center;">| Ȳₐ₂.</td>
<td style="text-align: center;">| Ȳ.₂.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
<td style="text-align: center;">...</td>
</tr>
<tr class="even">
<td style="text-align: center;">niveau a</td>
<td style="text-align: center;">Ȳ₁b.</td>
<td style="text-align: center;">| Ȳ₂b.</td>
<td style="text-align: center;">| ..</td>
<td style="text-align: center;">| Ȳₐb.</td>
<td style="text-align: center;">| Ȳ.b.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Moyenne Facteur B</td>
<td style="text-align: center;">Ȳ₁..</td>
<td style="text-align: center;">| Ȳ₂..</td>
<td style="text-align: center;">| ..</td>
<td style="text-align: center;">| Ȳₐ..</td>
<td style="text-align: center;">| Ȳ...</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math display">\[
\text{Estimé de l’effet global du niveau } i \text{ du facteur A :} \quad \overline{Y}_{i..} - \overline{Y}_{...}
\]</span></p>
<p><span class="math display">\[
\text{Estimé de l’effet global du niveau } j \text{ du facteur B :} \quad \overline{Y}_{.j.} - \overline{Y}_{...}
\]</span></p>
<p><span class="math display">\[
\text{Estimé de l’effet d’interaction entre le niveau } i \text{ du facteur A} \\
\text{et le niveau } j \text{ du facteur B :} \quad \overline{Y}_{ij.} - \overline{Y}_{i..} - \overline{Y}_{.j.} + \overline{Y}_{...}
\]</span></p>
</section>
<section id="décomposition-de-la-variabilité-totale" class="level4" data-number="1.5.2">
<h4 data-number="1.5.2" class="anchored" data-anchor-id="décomposition-de-la-variabilité-totale"><span class="header-section-number">1.5.2</span> Décomposition de la variabilité totale</h4>
<p>La variabilité totale (SSc) observée peut être décomposée en 4 parties :</p>
<p><span class="math display">\[
SS_c = SS_A + SS_B + SS_{AB} + SS_e
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un dataframe avec les formules et descriptions</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Formule"</span> <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SS_A = nb Σ (Ȳ_i.. - Ȳ_...)²"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SS_B = na Σ (Ȳ_.j. - Ȳ_...)²"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SS_AB = n Σ Σ (Ȳ_ij. - Ȳ_i.. - Ȳ_.j. + Ȳ_...)²"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SS_e = Σ Σ Σ (Y_ijk - Ȳ_ij.)²"</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Description"</span> <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Variabilité due aux différences entre les niveaux du facteur A"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Variabilité due aux différences entre les niveaux du facteur B"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Variabilité due aux interactions entre les niveaux du facteur A et ceux du facteur B"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Variabilité résiduelle qui n’est pas expliquée par les facteurs et est due aux erreurs aléatoires"</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le tableau </span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(df, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">caption =</span> <span class="st">"Tableau des sommes des carrés"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">background =</span> <span class="st">"#00CCFF"</span>, <span class="at">color =</span> <span class="st">"black"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tableau des sommes des carrés</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: rgba(0, 204, 255, 255) !important;">Formule</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: rgba(0, 204, 255, 255) !important;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">SS_A = nb Σ (Ȳ_i.. - Ȳ_...)²</td>
<td style="text-align: center;">| Variabilité due aux différences entre les niveaux du facteur A</td>
</tr>
<tr class="even">
<td style="text-align: center;">SS_B = na Σ (Ȳ_.j. - Ȳ_...)²</td>
<td style="text-align: center;">| Variabilité due aux différences entre les niveaux du facteur B</td>
</tr>
<tr class="odd">
<td style="text-align: center;">SS_AB = n Σ Σ (Ȳ_ij. - Ȳ_i.. - Ȳ_.j. + Ȳ_..</td>
<td style="text-align: center;">)² | Variabilité due aux interactions entre les niveaux du facteur A et ceux du facteur B</td>
</tr>
<tr class="even">
<td style="text-align: center;">SS_e = Σ Σ Σ (Y_ijk - Ȳ_ij.)²</td>
<td style="text-align: center;">| Variabilité résiduelle qui n’est pas expliquée par les facteurs et est due aux erreurs aléatoires</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="les-tests-dhypothèses-appropriées-dans-le-contexte-danova-à-deux-facteurs" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="les-tests-dhypothèses-appropriées-dans-le-contexte-danova-à-deux-facteurs"><span class="header-section-number">1.6</span> Les tests d’hypothèses appropriées dans le contexte d’ANOVA à deux facteurs</h3>
<p><span class="math display">\[
\text{Test sur l’interaction : basé sur la statistique } F =
\frac{\frac{SS_{AB}}{(a-1)(b-1)}}{\frac{SS_e}{ab(n-1)}}.
\]</span></p>
<p><span class="math display">\[
\text{Test sur l’effet global du facteur A : basé sur } F =
\frac{\frac{SS_A}{(a-1)}}{\frac{SS_e}{ab(n-1)}}.
\]</span></p>
<p><span class="math display">\[
\text{Test sur l’effet global du facteur B : basé sur } F =
\frac{\frac{SS_B}{(b-1)}}{\frac{SS_e}{ab(n-1)}}.
\]</span></p>
</section>
<section id="test-dinteraction-entre-les-facteurs" class="level3" data-number="1.7">
<h3 data-number="1.7" class="anchored" data-anchor-id="test-dinteraction-entre-les-facteurs"><span class="header-section-number">1.7</span> Test d’interaction entre les facteurs</h3>
<p>Existe-t-il une interaction significative entre le facteur source et reflex pour la variable crédibilité?</p>
<p>𝐻_0 :𝑖𝑙 𝑛′ 𝑦 𝑎 𝑝𝑎𝑠 𝑑′ 𝑖𝑛𝑡𝑒𝑟𝑎𝑐𝑡𝑖𝑜𝑛 𝑒𝑛𝑡𝑟𝑒 𝑙𝑒𝑠 𝑓𝑎𝑐𝑡𝑒𝑢𝑟𝑠<br>
𝐻_1 :𝑖𝑙 𝑦 𝑎 𝑢𝑛𝑒 𝑖𝑛𝑡𝑒𝑟𝑎𝑐𝑡𝑖𝑜𝑛 𝑒𝑛𝑡𝑟𝑒 𝑙𝑒𝑠 𝑓𝑎𝑐𝑡𝑒𝑢𝑟𝑠</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)  </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA avec interaction entre source et reflex</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>anova_source_reflex <span class="ot">&lt;-</span> <span class="fu">aov</span>(cred <span class="sc">~</span> source <span class="sc">*</span> reflex, <span class="at">data =</span> robtech)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats de l'ANOVA</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_source_reflex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
source          1  154.1  154.13  17.701 5.12e-05 ***
reflex          1   20.8   20.83   2.393    0.125    
source:reflex   1    2.1    2.13   0.245    0.622    
Residuals     116 1010.1    8.71                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p><em>P-value = 0.622</em> &gt; niveau de signification (α) = 0.05. donc <strong>on ne rejette pas l’hypothèse nulle.</strong></p></li>
<li><p>Au niveau de signification 5%, les données de nous fournissent pas assez de preuves pour conclure à une interaction statistiquement significative entre les facteurs.</p></li>
<li><p>On passe donc à l’<em>analyse des effets globaux</em> dans cette même table d’ANOVA.</p></li>
</ul>
</section>
<section id="analyse-fine-des-résultats-lorsque-linteraction-nest-pas-significative" class="level3" data-number="1.8">
<h3 data-number="1.8" class="anchored" data-anchor-id="analyse-fine-des-résultats-lorsque-linteraction-nest-pas-significative"><span class="header-section-number">1.8</span> Analyse fine des résultats lorsque l’interaction n’est pas significative</h3>
<ul>
<li><strong>Test de l’effet global du facteur Source:</strong></li>
</ul>
<p>𝐻_0 : 𝜇_𝑏𝑟𝑜𝑐ℎ𝑢𝑟𝑒 𝑑𝑢 𝑚𝑎𝑛𝑢𝑓𝑎𝑐𝑡𝑢𝑟𝑖𝑒𝑟=𝜇_𝑝𝑟𝑜𝑡𝑒𝑔𝑒𝑧 𝑣𝑜𝑢𝑠 vs.&nbsp;𝐻_1 :𝜇_𝑏𝑟𝑜𝑐ℎ𝑢𝑟𝑒 𝑑𝑢 𝑚𝑎𝑛𝑢𝑓𝑎𝑐𝑡𝑢𝑟𝑖𝑒𝑟≠𝜇_𝑝𝑟𝑜𝑡𝑒𝑔𝑒𝑧 𝑣𝑜𝑢𝑠</p>
<p>P-value=0.000, il y a une différence significative entre les moyennes marginales du facteur Source.</p>
<ul>
<li><p><strong>Test de l’effet global du facteur Reflex:</strong></p>
<p>𝐻_0 : 𝜇_𝑐𝑜𝑢𝑟𝑡=𝜇_𝑙𝑜𝑛𝑔 𝐻_1 :𝜇_𝑐𝑜𝑢𝑟𝑡≠𝜇_𝑙𝑜𝑛𝑔</p>
<p>P-value=0.125, il n’y a pas de différence significative entre les moyennes marginales du facteur Reflex.</p></li>
</ul>
<p>Pour chaque facteur dont <strong>l’effet est significatif</strong> :<br>
-Mesurer l’importance de l’effet (<strong>partial eta squared</strong>) ;</p>
<p>-S’intéresser à l’intervalle de confiance pour chaque <strong>moyenne marginale</strong> ;</p>
<p>-Comparer ces <strong>moyennes marginales</strong> entre elles à l’aide de méthodes de comparaisons multiples (tests et intervalles sur la différence entre les moyennes).</p>
<section id="estimated-marginal-means--source" class="level4" data-number="1.8.1">
<h4 data-number="1.8.1" class="anchored" data-anchor-id="estimated-marginal-means--source"><span class="header-section-number">1.8.1</span> Estimated Marginal means- Source</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#installer emmeans</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"emmeans"</span>, <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>le package 'emmeans' a été décompressé et les sommes MD5 ont été vérifiées avec succés

Les packages binaires téléchargés sont dans
    C:\Users\Fatou\AppData\Local\Temp\RtmpkfiCQ5\downloaded_packages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger la bibliothèque</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Moyenne estimé</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Anova test</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>anova_estime <span class="ot">&lt;-</span> <span class="fu">aov</span>(cred <span class="sc">~</span> source, <span class="at">data =</span> robtech)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenir les moyennes marginales estimées</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>moyenne_estime <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_estime, <span class="sc">~</span> source)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(moyenne_estime)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> source emmean    SE  df lower.CL upper.CL
 1        6.95 0.382 118     6.19     7.71
 2        9.22 0.382 118     8.46     9.97

Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaisons par paires </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>pairwise <span class="ot">&lt;-</span> <span class="fu">pairs</span>(moyenne_estime)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate   SE  df t.ratio p.value
 source1 - source2    -2.27 0.54 118  -4.196  0.0001</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test univarié</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>univarie <span class="ot">&lt;-</span> <span class="fu">Anova</span>(anova_estime, <span class="at">type =</span> <span class="st">"III"</span>)  </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(univarie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: cred
             Sum Sq  Df F value    Pr(&gt;F)    
(Intercept) 2898.15   1 331.046 &lt; 2.2e-16 ***
source       154.13   1  17.606 5.289e-05 ***
Residuals   1033.03 118                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="estimated-marginal-means--reflex" class="level4" data-number="1.8.2">
<h4 data-number="1.8.2" class="anchored" data-anchor-id="estimated-marginal-means--reflex"><span class="header-section-number">1.8.2</span> Estimated Marginal means- Reflex</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Moyenne estimé</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Anova test</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>anova_estime_reflex <span class="ot">&lt;-</span> <span class="fu">aov</span>(cred <span class="sc">~</span> reflex, <span class="at">data =</span> robtech)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenir les moyennes marginales estimées</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>moyenne_estime_reflex <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_estime_reflex, <span class="sc">~</span> reflex)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(moyenne_estime_reflex)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> reflex emmean    SE  df lower.CL upper.CL
 1        8.50 0.406 118     7.70     9.30
 2        7.67 0.406 118     6.86     8.47

Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaisons par paires </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>pairwise_reflex <span class="ot">&lt;-</span> <span class="fu">pairs</span>(moyenne_estime_reflex)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pairwise_reflex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate    SE  df t.ratio p.value
 reflex1 - reflex2    0.833 0.574 118   1.452  0.1492</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test univarié</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>univarie_reflex <span class="ot">&lt;-</span> <span class="fu">Anova</span>(anova_estime_reflex, <span class="at">type =</span> <span class="st">"III"</span>)  </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(univarie_reflex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: cred
            Sum Sq  Df  F value Pr(&gt;F)    
(Intercept) 4335.0   1 438.5796 &lt;2e-16 ***
reflex        20.8   1   2.1077 0.1492    
Residuals   1166.3 118                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="test-dinteraction-entre-les-facteurs-1" class="level3" data-number="1.9">
<h3 data-number="1.9" class="anchored" data-anchor-id="test-dinteraction-entre-les-facteurs-1"><span class="header-section-number">1.9</span> Test d’interaction entre les facteurs</h3>
<p>Existe-t-il une interaction significative entre le facteur source et reflex pour la variable évaluation?</p>
<p>𝐻_0 :𝑖𝑙 𝑛′ 𝑦 𝑎 𝑝𝑎𝑠 𝑑′ 𝑖𝑛𝑡𝑒𝑟𝑎𝑐𝑡𝑖𝑜𝑛 𝑒𝑛𝑡𝑟𝑒 𝑙𝑒𝑠 𝑓𝑎𝑐𝑡𝑒𝑢𝑟𝑠<br>
𝐻_1 :𝑖𝑙 𝑦 𝑎 𝑢𝑛𝑒 𝑖𝑛𝑡𝑒𝑟𝑎𝑐𝑡𝑖𝑜𝑛 𝑒𝑛𝑡𝑟𝑒 𝑙𝑒𝑠 𝑓𝑎𝑐𝑡𝑒𝑢𝑟𝑠</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA avvec intercation entre eval et source</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>anova_eval_source <span class="ot">&lt;-</span> <span class="fu">aov</span>(eval <span class="sc">~</span> source <span class="sc">*</span> reflex, <span class="at">data =</span> robtech)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats de l'ANOVA</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_eval_source)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
source          1    7.5    7.50   0.916 0.340489    
reflex          1   13.3   13.33   1.629 0.204440    
source:reflex   1  108.3  108.30  13.229 0.000413 ***
Residuals     116  949.7    8.19                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>P-value = 0.000 &gt; niveau de signification (α) = 0.05 donc on rejette l’hypothèse nulle.</p></li>
<li><p>Au seuil de signification 5%, on peut conclure à une interaction statistiquement significative entre les facteurs.</p></li>
<li><p>L’effet d’un facteur est diffèrent selon le niveau de l’autre facteur.</p></li>
<li><p>On ne s’intéresse plus aux effets globaux.</p></li>
<li><p>On passe donc à l’analyse fine des résultats c.à.d. explorer l’effet d’un facteur à l’intérieur de chaque niveau de l’autre.</p></li>
</ul>
</section>
<section id="analyse-fine-des-résultats-lorsque-linteraction-est-significative" class="level3" data-number="1.10">
<h3 data-number="1.10" class="anchored" data-anchor-id="analyse-fine-des-résultats-lorsque-linteraction-est-significative"><span class="header-section-number">1.10</span> Analyse fine des résultats lorsque l’interaction est significative</h3>
<p>On voudra explorer l’effet d’un facteur à l’intérieur de chaque niveau de l’autre.</p>
<ul>
<li><p>Les différences entre les moyennes d’un facteur pour un niveau donné de l’autre facteur sont appelées « <strong>effets simples</strong> ».</p></li>
<li><p>Par exemple, on pourra comparer les moyennes du facteur A pour un niveau fixé, j disons, du facteur B. C’est-à-dire comparer entre elles les moyennes μ1j, μ2j , …, μaj. Cette comparaison peut être effectuée pour chaque niveau du facteur B.</p></li>
<li><p>De même, on pourra comparer les moyennes du facteur B pour un niveau fixé, i disons, du facteur A. C’est-à-dire comparer entre elles μi1 , μi2 , …, μib. -Cette comparaison peut être effectuée pour chaque niveau du facteur A.</p></li>
<li><p>En R, lorsque les facteurs ont deux niveaux, une manière de procéder est de réécrire le modèle comme une ANOVA à un facteur et d’utiliser la fonction aov() pour effectuer une ANOVA à un facteur.</p></li>
</ul>
</section>
<section id="création-des-groupes" class="level3" data-number="1.11">
<h3 data-number="1.11" class="anchored" data-anchor-id="création-des-groupes"><span class="header-section-number">1.11</span> Création des groupes</h3>
<p>Un modèle d’ANOVA à deux facteurs contrôlés A et B comportant a et b niveaux respectivement peut toujours être réécrit comme un modèle d’<strong>ANOVA à un facteur contrôlé avec a * b niveaux (ou groupes)</strong>.</p>
<p><strong>Retour à l’exemple:</strong></p>
<p>Comme il y a une interaction significative pour la variable « évaluation », effectuons la comparaison des moyennes d’un facteur séparément selon les niveaux de l’autre facteur.</p>
<p>Dans le fichier de données «&nbsp;Anova_ex2.csv&nbsp;», la variable « groupe » est définie de la manière suivante :</p>
<p>1 → groupe brochure du manufacturier et temps de réflexion <strong>court</strong> 2→ groupe brochure du manufacturier et temps de réflexion <strong>long</strong> 3 → groupe protégez vous et temps de réflexion <strong>court</strong> 4 → groupe protégez vous et temps de réflexion <strong>long</strong></p>
</section>
<section id="syntaxe-pour-la-création-des-groupes" class="level3" data-number="1.12">
<h3 data-number="1.12" class="anchored" data-anchor-id="syntaxe-pour-la-création-des-groupes"><span class="header-section-number">1.12</span> Syntaxe pour la création des groupes</h3>
<p>Pour créer cette nouvelle variable groupe on peut utiliser les commandes suivantes sur R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer la variable groupe avec ifelse</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>robtech<span class="sc">$</span>groupe <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(robtech<span class="sc">$</span>source <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> robtech<span class="sc">$</span>reflex <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(robtech<span class="sc">$</span>source <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> robtech<span class="sc">$</span>reflex <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">2</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(robtech<span class="sc">$</span>source <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> robtech<span class="sc">$</span>reflex <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">3</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(robtech<span class="sc">$</span>source <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> robtech<span class="sc">$</span>reflex <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">4</span>, <span class="cn">NA</span>))))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>robtech<span class="sc">$</span>groupe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(robtech<span class="sc">$</span>groupe) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools) <span class="co"># Pour le test LSD post-hoc</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA- eval-groupe</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>anova_groupe <span class="ot">&lt;-</span> <span class="fu">aov</span>(eval <span class="sc">~</span> groupe, <span class="at">data =</span> robtech)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaisons post-hoc LSD </span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>posthoc <span class="ot">&lt;-</span> <span class="fu">PostHocTest</span>(anova_groupe, <span class="at">method =</span> <span class="st">"lsd"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultat</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(posthoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Posthoc multiple comparisons of means : Fisher LSD 
    95% family-wise confidence level

$groupe
          diff     lwr.ci     upr.ci    pval    
2-1 -1.2333333 -2.6965662 0.22989954 0.09773 .  
3-1 -1.4000000 -2.8632329 0.06323287 0.06058 .  
4-1  1.1666667 -0.2965662 2.62989954 0.11701    
3-2 -0.1666667 -1.6298995 1.29656621 0.82191    
4-2  2.4000000  0.9367671 3.86323287 0.00152 ** 
4-3  2.5666667  1.1034338 4.02989954 0.00072 ***

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Retour à l’exemple:</p>
<p>Hypothèses d’intérêt pour l’analyse des effets simples du facteur source sur l’évaluation moyenne ?</p>
<p><strong>Si Reflex = court</strong> On compare les moyennes des groupes 1&amp;3 (revoir la définition des groupes)</p>
<p><strong>Si Reflex= long</strong> On compare les moyennes des groupes 2&amp;4</p>
<p>Hypothèses d’intérêt pour l’analyse des effets simples du facteur reflex sur l’évaluation moyenne ?</p>
<p><strong>Si Source = brochure du manufacturier</strong> On compare les moyennes des groupes 1&amp;2</p>
<p><strong>Si Source = Protégez vous</strong> On compare les moyennes des groupes 3&amp;4</p>
<p><strong>Exercice:</strong> effectuer les tests d’hypothèses et conclure dans le contexte du problème (implications managériales).</p>
</section>
</section>
<section id="partie-2-anova-à-deux-facteurs-controlés-cellules-déséquilibrées" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="partie-2-anova-à-deux-facteurs-controlés-cellules-déséquilibrées"><span class="header-section-number">2</span> Partie 2: ANOVA à deux facteurs controlés: cellules déséquilibrées</h2>
<section id="mise-en-situation-1" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="mise-en-situation-1"><span class="header-section-number">2.1</span> Mise en situation 1</h3>
<p>Ce contexte est inspiré de l’article&nbsp; «&nbsp;&nbsp;Small, D. A. et Verrochi, N. M. (2009). The Face of Need: Facial Emotion Expression on Charity Advertisements. Journal of Marketing Research XLVI, 777-787 » Dans l’article, cinq expériences sont menées afin d’étudier l’impact des photographies montrées dans le but de susciter de la sympathie et d’inciter au don. Nous allons faire deux 2 ANOVA à 2 facteurs contrôlés dans le cas où les cellules ne sont pas équilibrées.</p>
<p>Les données se trouvent dans le fichier «&nbsp;Charity.sav&nbsp;».</p>
<p><strong>Les 2 variables dépendantes sont&nbsp;:</strong> <em>Don:</em> montant d’argent donnée par le participant (voir l’étude 1) variant entre 1 et 10. <em>Sympathie</em><strong>:</strong> score de sympathie (voir l’étude 2) variant entre 1 et 7. Plus le score est élevé, plus le participant ressent de la sympathie envers l’enfant montré sur la photo.</p>
<p><strong>Les 2 facteurs contrôlés sont&nbsp;:</strong> <em>Enfant</em>&nbsp;: enfant sur la photo (1=enfant #1, 2=enfant #2). <em>Émotion</em>&nbsp;: émotion affichée par l’enfant sur la photo (1=heureux, 2=neutre, 3=triste).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le fichier CSV </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>charity <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">Fatou</span><span class="sc">\\</span><span class="st">OneDrive - HEC Montréal</span><span class="sc">\\</span><span class="st">PROJET SUPERVISE</span><span class="sc">\\</span><span class="st">THEME 4</span><span class="sc">\\</span><span class="st">data</span><span class="sc">\\</span><span class="st">Charity.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>enfant<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(charity<span class="sc">$</span>enfant)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>emotion<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(charity<span class="sc">$</span>emotion)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remplacer la virgule par un point</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>sympathie <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, charity<span class="sc">$</span>sympathie)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir en numérique</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>sympathie <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(charity<span class="sc">$</span>sympathie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="variable-don" class="level4" data-number="2.1.1">
<h4 data-number="2.1.1" class="anchored" data-anchor-id="variable-don"><span class="header-section-number">2.1.1</span> Variable Don</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les bibliothèques nécessaires</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives de la variable don</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>don_stat <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant, emotion) <span class="sc">%&gt;%</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(don, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">sd</span>(don, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>()</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(don_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   enfant [2]
  enfant emotion Moyenne Ecart_Type     N
  &lt;fct&gt;  &lt;fct&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 1      1          3.28       2.71    29
2 1      2          2.45       2.52    22
3 1      3          4.32       3.00    25
4 2      1          2.64       2.16    25
5 2      2          2.17       2.49    29
6 2      3          4.52       2.48    21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger ggplot2</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le graphique des moyennes marginales</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(don_stat, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(enfant), <span class="at">y =</span> Moyenne, <span class="at">group =</span> <span class="fu">factor</span>(emotion), <span class="at">color =</span> <span class="fu">factor</span>(emotion))) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>   </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>    </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moyenne marginale estimé de la variable don"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"enfant"</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Moyenne marginale estimé"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"emotion"</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne des dons par enfant par emotion</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>don_moyenne_enfant_emotion <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant, emotion) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(don, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne des dons par enfant toutes emotions confondus</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>don_moyenne_enfant <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant) <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(don, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">emotion =</span> <span class="st">"Moyenne totale par enfant"</span>) </span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne des dons par emotion</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>don_moyenne_emotion <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(emotion) <span class="sc">%&gt;%</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(don, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">enfant =</span> <span class="st">"Moyenne totale par emotion"</span>)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Combiner les trois tableaux ensemble</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>don_moyenne_final <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(don_moyenne_enfant_emotion, don_moyenne_enfant, don_moyenne_emotion)</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>don_moyenne_final</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
# Groups:   enfant [3]
   enfant                     emotion                   Moyenne
   &lt;chr&gt;                      &lt;chr&gt;                       &lt;dbl&gt;
 1 1                          1                            3.28
 2 1                          2                            2.45
 3 1                          3                            4.32
 4 2                          1                            2.64
 5 2                          2                            2.17
 6 2                          3                            4.52
 7 1                          Moyenne totale par enfant    3.38
 8 2                          Moyenne totale par enfant    2.99
 9 Moyenne totale par emotion 1                            2.98
10 Moyenne totale par emotion 2                            2.29
11 Moyenne totale par emotion 3                            4.41</code></pre>
</div>
</div>
</section>
<section id="variable-sympathie" class="level4" data-number="2.1.2">
<h4 data-number="2.1.2" class="anchored" data-anchor-id="variable-sympathie"><span class="header-section-number">2.1.2</span> Variable sympathie</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives de la variable don</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sympathie_stat <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant, emotion) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(sympathie, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">sd</span>(sympathie, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>()</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sympathie_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   enfant [2]
  enfant emotion Moyenne Ecart_Type     N
  &lt;fct&gt;  &lt;fct&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 1      1          3.53       1.44    29
2 1      2          3.14       1.39    22
3 1      3          5.08       1.40    25
4 2      1          3.14       1.29    25
5 2      2          2.95       1.41    29
6 2      3          3.32       1.36    21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le graphique des moyennes marginales</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sympathie_stat, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(emotion), <span class="at">y =</span> Moyenne, <span class="at">group =</span> <span class="fu">factor</span>(enfant), <span class="at">color =</span> <span class="fu">factor</span>(enfant))) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>   </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>    </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moyenne marginale estimé de la variable sympathie"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"emotion"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Moyenne marginale estimé"</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"enfant"</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_S4_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger la bibliothèque nécessaire</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne de sympathie par enfant par émotion</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>sympathie_moyenne_enfant_emotion <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant, emotion) <span class="sc">%&gt;%</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(sympathie, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne de sympathie par enfant (toutes émotions confondues)</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>sympathie_moyenne_enfant <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(enfant) <span class="sc">%&gt;%</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(sympathie, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">emotion =</span> <span class="st">"Moyenne totale par enfant"</span>)  <span class="co"># Ajouter un label "Total" pour identifier cette ligne</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne de sympathie par émotion (tous enfants confondus)</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>sympathie_moyenne_emotion <span class="ot">&lt;-</span> charity <span class="sc">%&gt;%</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(emotion) <span class="sc">%&gt;%</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Moyenne =</span> <span class="fu">mean</span>(sympathie, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">enfant =</span> <span class="st">"Moyenne totale par emotion"</span>)  <span class="co"># Ajouter un label "Total"</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Combiner les trois tableaux ensemble</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>sympathie_moyenne_final <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(sympathie_moyenne_enfant_emotion, sympathie_moyenne_enfant, sympathie_moyenne_emotion)</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le tableau final</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sympathie_moyenne_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   enfant                     emotion                   Moyenne
   &lt;chr&gt;                      &lt;chr&gt;                       &lt;dbl&gt;
 1 1                          1                            3.53
 2 1                          2                            3.14
 3 1                          3                            5.08
 4 2                          1                            3.14
 5 2                          2                            2.95
 6 2                          3                            3.32
 7 1                          Moyenne totale par enfant    3.93
 8 2                          Moyenne totale par enfant    3.11
 9 Moyenne totale par emotion 1                            3.35
10 Moyenne totale par emotion 2                            3.03
11 Moyenne totale par emotion 3                            4.27</code></pre>
</div>
</div>
</section>
</section>
<section id="décomposition-de-la-variabilité-totale-anova-à-2-facteurs-avec-cellules-déséquilibrées" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="décomposition-de-la-variabilité-totale-anova-à-2-facteurs-avec-cellules-déséquilibrées"><span class="header-section-number">2.2</span> Décomposition de la variabilité totale: ANOVA à 2 facteurs avec cellules déséquilibrées</h3>
<p>Il y a plusieurs manières de décomposer la variabilité totale observée (mesurée par des sommes de carrés).</p>
<p>Dans le cas de cellules déséquilibrées, la moyenne pondérée des moyennes des cellules pour un niveau donné d’un facteur n’est pas nécessairement égale à la moyenne marginale du même niveau du facteur.</p>
<p>La plupart des logiciels offrent 4 possibilités pour la décomposition de la somme des carrés totale : type I, type II, type III et type IV. Ces 4 méthodes donnent des résultats identiques lorsque les cellules sont équilibrées, mais ce n’est plus vrai dans le cas de cellules déséquilibrées.</p>
<p>Le but ici est de tester des hypothèses concernant des différences entre des moyennes de « populations »; il faut donc utiliser les moyennes marginales (et non les moyennes pondérées). On choisit généralement les sommes de carrés de type III .</p>
</section>
<section id="analyse-de-la-variable-don" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="analyse-de-la-variable-don"><span class="header-section-number">2.3</span> Analyse de la variable Don</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA avec interaction entre enfant et emotion</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion <span class="ot">&lt;-</span> <span class="fu">aov</span>(don <span class="sc">~</span> enfant <span class="sc">*</span> emotion, <span class="at">data =</span> charity)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion_resultat <span class="ot">&lt;-</span> <span class="fu">Anova</span>(anova_enfant_emotion, <span class="at">type =</span> <span class="st">"III"</span>)  <span class="co"># Type III sélectionné</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion_resultat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: don
               Sum Sq  Df F value    Pr(&gt;F)    
(Intercept)    311.21   1 46.8187 2.031e-10 ***
enfant           5.43   1  0.8167   0.36766    
emotion         41.25   2  3.1026   0.04793 *  
enfant:emotion   4.36   2  0.3278   0.72103    
Residuals      963.82 145                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>L’interaction entre les deux facteurs n’est pas significative (p-value = 0.721). On peut donc procéder à <strong>l’analyse des effets globaux</strong>.</p>
<p>Analyse des effets globaux (variable Don)</p>
<ul>
<li><p><strong>Pour le facteur «&nbsp;enfant&nbsp;»</strong> Soit µ_𝑖 le don marginal pour l’enfant #i. On veut tester 𝐻0 : µ_1 = µ_2 𝐻1 : µ_1 ≠ µ_2 Le facteur «&nbsp;enfant&nbsp;» n’est pas globalement significatif pour expliquer le don.</p></li>
<li><p><strong>Pour le facteur «&nbsp;émotion&nbsp;»</strong> Soit le µ_𝑖 don moyen marginal pour l’émotion i. On teste 𝐻0 : µ_1 = µ_2=𝜇_3 𝐻1 : Au moins deux moyennes sont différentes. L’effet global du facteur «&nbsp;emotion&nbsp;» est significatif (p-value=0%).</p></li>
</ul>
<p><strong>Questions</strong></p>
<p>1-Présentez les tests à effectuer pour le facteur «&nbsp;émotion&nbsp;». 2- Interprétez les résultats dans le contexte du problème.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer un ANOVA </span><span class="al">TEST</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>anova_don <span class="ot">&lt;-</span> <span class="fu">aov</span>(don <span class="sc">~</span> emotion, <span class="at">data =</span> charity)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Faire les estimations marginales des moyennes</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>emmeans_don <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_don, <span class="sc">~</span> emotion)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(emmeans_don)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> emotion emmean    SE  df lower.CL upper.CL
 1         2.98 0.349 148     2.29     3.67
 2         2.29 0.359 148     1.59     3.00
 3         4.41 0.378 148     3.67     5.16

Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#Comparaisons par paires avec correction LSD </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pairwise_don <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emmeans_don, <span class="at">adjust =</span> <span class="st">"none"</span>)  </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pairwise_don)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast            estimate    SE  df t.ratio p.value
 emotion1 - emotion2    0.687 0.500 148   1.375  0.1714
 emotion1 - emotion3   -1.432 0.514 148  -2.786  0.0060
 emotion2 - emotion3   -2.119 0.521 148  -4.069  0.0001</code></pre>
</div>
</div>
<p><strong>Résultats:</strong></p>
<p>-Lorsque l’émotion affichée est la tristesse, la moyenne des dons est significativement différente des deux autres types d’émotion (joie et neutralité). -En particulier la tristesse suscite un don moyen supérieur de $0.438 à $2.49 à la joie et un don moyen supérieur de $1.065 à $3.151 à la neutralité au niveau 95%.</p>
</section>
<section id="analyse-de-la-variable-sympathie" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="analyse-de-la-variable-sympathie"><span class="header-section-number">2.4</span> Analyse de la variable Sympathie</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA avec interaction entre enfant et emotion</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion_sympathie <span class="ot">&lt;-</span> <span class="fu">aov</span>(sympathie <span class="sc">~</span> enfant <span class="sc">*</span> emotion, <span class="at">data =</span> charity)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion_sympathie_resultat <span class="ot">&lt;-</span> <span class="fu">Anova</span>(anova_enfant_emotion_sympathie, <span class="at">type =</span> <span class="st">"III"</span>)  <span class="co"># Type III sélectionné</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>anova_enfant_emotion_sympathie_resultat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: sympathie
               Sum Sq  Df  F value    Pr(&gt;F)    
(Intercept)    361.65   1 188.0837 &lt; 2.2e-16 ***
enfant           2.10   1   1.0937    0.2974    
emotion         51.22   2  13.3187 4.896e-06 ***
enfant:emotion  17.18   2   4.4673    0.0131 *  
Residuals      278.81 145                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>L’interaction est statistiquement significative (p-value = 0.013) au niveau 0.05. On doit donc évaluer les effets simples des facteurs.</p>
</section>
<section id="analyse-des-effets-simples-des-facteurs-variable-sympathie" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="analyse-des-effets-simples-des-facteurs-variable-sympathie"><span class="header-section-number">2.5</span> Analyse des effets simples des facteurs (variable Sympathie)</h3>
<p>le facteur Enfant comporte 2 niveaux et le facteur émotion comporte 3 niveaux. On va donc créer 6 groupes (2*3):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer la variable "groupe" </span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>groupe <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(charity<span class="sc">$</span>emotion <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> charity<span class="sc">$</span>enfant <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(charity<span class="sc">$</span>emotion <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> charity<span class="sc">$</span>enfant <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">2</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(charity<span class="sc">$</span>emotion <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> charity<span class="sc">$</span>enfant <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">3</span>,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(charity<span class="sc">$</span>emotion <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> charity<span class="sc">$</span>enfant <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">4</span>,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(charity<span class="sc">$</span>emotion <span class="sc">==</span> <span class="dv">3</span> <span class="sc">&amp;</span> charity<span class="sc">$</span>enfant <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>)))))</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>charity<span class="sc">$</span>groupe<span class="ot">&lt;-</span><span class="fu">as.factor</span>(charity<span class="sc">$</span>groupe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Questions</strong></p>
<p>-Quelles sont les hypothèses d’intérêt pour l’analyse des effets simples du facteur «&nbsp;enfant&nbsp;» (2 niveaux) sur la sympathie moyenne ? - Quelles sont les hypothèses d’intérêt pour l’analyse des effets simples du facteur «&nbsp;émotion&nbsp;» (3 niveaux) sur sympathie moyenne ?</p>
<p><strong>Effets simples pour le facteur «&nbsp;enfant&nbsp;»</strong></p>
<p>Lorsque «&nbsp;émotion = 1&nbsp;» heureux 𝐻0 : µ_1 = µ_2 vs.&nbsp;𝐻1 : µ_1 ≠ µ_2</p>
<p>Lorsque «&nbsp;émotion = 2&nbsp;» neutre 𝐻0 : µ_3 = µ_4 vs.&nbsp;𝐻1 : µ_3 ≠ µ_4</p>
<p>Lorsque «&nbsp;émotion = 3&nbsp;» triste 𝐻0 : µ_5 = µ_6 vs.&nbsp;𝐻1 : µ_5 ≠ µ_6</p>
<p><strong>Effets simples pour le facteur «&nbsp;émotion&nbsp;»</strong></p>
<p>Chez l’enfant #1: Comparaison 1,3 et 5 𝐻0 : µ_1 = µ_3 = µ_5 vs.&nbsp;𝐻1 : 𝐴𝑢 𝑚𝑜𝑖𝑛𝑠 𝑑𝑒𝑢𝑥 𝑚𝑜𝑦𝑒𝑛𝑛𝑒𝑠 𝑠𝑜𝑛𝑡 𝑑𝑖𝑓𝑓é𝑟𝑒𝑛𝑡𝑒𝑠.</p>
<p>Chez l’enfant #2: Comparaison 2,4 et 6 𝐻0 : µ_2 = µ_4 = µ_6 vs.&nbsp;𝐻1 : 𝐴𝑢 𝑚𝑜𝑖𝑛𝑠 𝑑𝑒𝑢𝑥 𝑚𝑜𝑦𝑒𝑛𝑛𝑒𝑠 𝑠𝑜𝑛𝑡 𝑑𝑖𝑓𝑓é𝑟𝑒𝑛𝑡𝑒𝑠.</p>
</section>
<section id="comparaison-des-moyennes" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="comparaison-des-moyennes"><span class="header-section-number">2.6</span> Comparaison des moyennes</h3>
<p>Pour comparer les moyennes après une ANOVA à deux facteurs, on regroupe les niveaux des facteurs dans une nouvelle variable pour faire une ANOVA à un seul facteur. Ensuite, on effectue des comparaisons post-hoc pour évaluer les différences entre les groupes.</p>
<p>Transformation de l’ANOVA à 2 facteurs en ANOVA à 1 facteur :</p>
<ul>
<li><p>On a crée une nouvelle variable groupe qui combine les facteurs enfant et emotion.</p></li>
<li><p>Cette variable est utilisée comme facteur unique dans l’ANOVA à un facteur.</p></li>
</ul>
<p><strong>Effets simples pour le facteur ‘’enfant’’</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA </span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>anova_sympathie <span class="ot">&lt;-</span> <span class="fu">aov</span>(sympathie <span class="sc">~</span> groupe, <span class="at">data =</span> charity)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Comparaisons par paires avec correction LSD </span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>pairwise_sympathie <span class="ot">&lt;-</span> <span class="fu">pairs</span>(<span class="fu">emmeans</span>(anova_sympathie , <span class="sc">~</span> groupe), <span class="at">adjust =</span> <span class="st">"none"</span>)  <span class="co"># "none" pour LSD sans correction</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pairwise_sympathie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate    SE  df t.ratio p.value
 groupe1 - groupe2  0.39578 0.378 145   1.046  0.2974
 groupe1 - groupe3  0.39411 0.392 145   1.005  0.3165
 groupe1 - groupe4  0.58586 0.364 145   1.609  0.1098
 groupe1 - groupe5 -1.54382 0.378 145  -4.079  0.0001
 groupe1 - groupe6  0.21424 0.397 145   0.539  0.5906
 groupe2 - groupe3 -0.00167 0.405 145  -0.004  0.9967
 groupe2 - groupe4  0.19008 0.378 145   0.502  0.6162
 groupe2 - groupe5 -1.93960 0.392 145  -4.945  &lt;.0001
 groupe2 - groupe6 -0.18154 0.410 145  -0.442  0.6589
 groupe3 - groupe4  0.19176 0.392 145   0.489  0.6255
 groupe3 - groupe5 -1.93793 0.405 145  -4.781  &lt;.0001
 groupe3 - groupe6 -0.17987 0.423 145  -0.425  0.6713
 groupe4 - groupe5 -2.12968 0.378 145  -5.628  &lt;.0001
 groupe4 - groupe6 -0.37163 0.397 145  -0.935  0.3512
 groupe5 - groupe6  1.75806 0.410 145   4.283  &lt;.0001</code></pre>
</div>
</div>
<p><strong>Conclusion&nbsp;:</strong> Ainsi, les enfants #1 et #2 suscite des sympathies moyennes différente seulement lorsqu’ils affichent la tristesse. Dans ce cas, la sympathie moyenne est de 0.94 à 2.56 points plus élevée (<strong>Intervalle de confiance</strong>) chez l’enfant #1 que chez l’enfant #2 <strong>au niveau 95%</strong>.</p>
<p><strong>Effet simples pour le facteur ‘’émotion’’</strong></p>
<p>###REVOIR AVEC LA PROFF LA PARTIE SUR LES CONTRASTE</p>
<p>Pour tester l’égalité des moyennes des trois niveaux du facteur émotion à l’intérieur de chaque niveau du facteur <strong>enfant</strong>, on doit utiliser un test <strong>ANOVA avec contrastes</strong>.</p>
<p>Il faut d’abord calculer manuellement les contrastes et ensuite les appliquer à la variable avant d’exécuter l’ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition des contrastes </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>contraste1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)  <span class="co"># Premier contraste</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>contraste2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)  <span class="co"># Deuxième contraste</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Faire une matrice des contrastes</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>contraste_matrice <span class="ot">&lt;-</span> <span class="fu">cbind</span>(contraste1, contraste2)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Appliquer les contrastes à la variable groupe</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(charity<span class="sc">$</span>groupe) <span class="ot">&lt;-</span> contraste_matrice</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer l'ANOVA avec les contrastes</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>anova_contrastes <span class="ot">&lt;-</span> <span class="fu">Anova</span>(<span class="fu">aov</span>(sympathie <span class="sc">~</span> groupe, <span class="at">data =</span> charity), <span class="at">type =</span> <span class="st">"III"</span>)</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_contrastes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: sympathie
             Sum Sq  Df  F value    Pr(&gt;F)    
(Intercept) 1846.76   1 960.4518 &lt; 2.2e-16 ***
groupe        77.82   5   8.0945 9.259e-07 ***
Residuals    278.81 145                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Custom Hypothesis Test 1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrer les données pour enfant == 1</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>charity_enfant1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(charity, enfant <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer une ANOVA</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>anova_enfant1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(sympathie <span class="sc">~</span> emotion, <span class="at">data =</span> charity_enfant1)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_enfant1)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)    
emotion      2  51.22  25.609   12.81 1.7e-05 ***
Residuals   73 145.93   1.999                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir les contrastes pour emotion</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>contraste1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>)  <span class="co"># Comparaison entre heureux et triste</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>contraste2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)  <span class="co"># Comparaison entre neutre et les autres</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer le test d'hypothèse avec linearHypothesis</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Tester les hypothèses</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(anova_enfant1, <span class="st">"emotion2 - (Intercept) = 0"</span>)  <span class="co"># Comparaison neutre - heureux</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
- (Intercept)  + emotion2 = 0

Model 1: restricted model
Model 2: sympathie ~ emotion

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     74 229.95                                  
2     73 145.93  1    84.028 42.035 9.307e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(anova_enfant1, <span class="st">"emotion3 - (Intercept) = 0"</span>)  <span class="co"># Comparaison triste - heureux</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
- (Intercept)  + emotion3 = 0

Model 1: restricted model
Model 2: sympathie ~ emotion

  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1     74 168.13                                
2     73 145.93  1    22.202 11.107 0.001353 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Custom Hypothesis Test 1</p>
</section>
<section id="conclusion" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">2.7</span> Conclusion&nbsp;:</h3>
<ul>
<li><p>L’émotion n’est significative pour expliquer la sympathie que chez l’enfant #1.</p></li>
<li><p>Lorsque l’enfant affiche une tristesse, la sympathie moyenne est significativement plus élevée comparativement aux autres émotions (voir tableau de LSD).</p></li>
<li><p>La tristesse chez l’enfant #1 suscite une sympathie moyenne plus élevée de 1.13 à 2.7 points que la neutralité au niveau 95%.</p></li>
</ul>
</section>
<section id="mise-en-situation-2" class="level3" data-number="2.8">
<h3 data-number="2.8" class="anchored" data-anchor-id="mise-en-situation-2"><span class="header-section-number">2.8</span> Mise en situation 2</h3>
<p>Un concessionnaire automobile souhaite étudier la consommation des véhicules en carburant selon la marque du véhicule et le type de conduite. Il recueille des données sur un échantillon de 206 véhicules contenues dans le fichier «&nbsp;consommation.sav&nbsp;». <strong>La variable dépendante</strong> étudiée est: Cons: la consommation en carburant en litres sur un trajet de 100 km. <strong>Les deux facteurs contrôlés</strong> sont: <strong>Conduite</strong> : le type de conduite = 1 si la conduite est jugée économique, 2 sinon. <strong>Marque</strong> : la marque de voiture= 1, 2 ou 3 (des voitures de la même catégorie).</p>
<p><strong>Question:</strong> Analysez, selon ce qui est pertinent, les effets globaux ou les effets simples des facteurs conduite et marque sur la consommation en carburant.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>